"""empty message

Revision ID: 66bc0bf59df8
Revises: 18cd64e72c0e
Create Date: 2022-08-15 10:38:14.450756

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '66bc0bf59df8'
down_revision = '18cd64e72c0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'type',
               existing_type=postgresql.ENUM('skin_care', 'makeup', 'fragrance', 'body', 'hair', 'accessory', 'wellness', 'other', name='categorytype'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'type',
               existing_type=postgresql.ENUM('skin_care', 'makeup', 'fragrance', 'body', 'hair', 'accessory', 'wellness', 'other', name='categorytype'),
               nullable=False)
    # ### end Alembic commands ###
